"use client";

import "../styles/globals.css";

// components
import Footer from "../components/Footer";
import Header from "../components/Header";

import { ThemeProvider } from "next-themes";

// export const metadata = {
//   title: "Portfólio - Gustavo Santana",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body>
        <ThemeProvider attribute="class" enableSystem={true}>
          <Header />
          <div className="h-px bg-gray-300 bg-gradient-line"></div>
          {children}
          <div className="h-px bg-gray-300 bg-gradient-line"></div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
